In [5]:



import fxcmpy
import pandas
import numpy as np
#import pytl.hull_moving_average import hull_moving_average as hull_moving_average

In [6]:


token = "8be2aeea31de5a526ac6d6580b03f5973142cdaa"
api = fxcmpy.fxcmpy(access_token=token, log_level='error',log_file=None,server='demo')
#con.is_connected

In [30]:
#getting candle data
pair='USD/JPY'
granularity='H1'
df = api.get_candles(pair,period=granularity,
                    start = dt.datetime(2022, 1, 1),
                    end = dt.datetime(2022,4,1)
                    )

In [15]:
df.head()
#df.drop_duplicates(keep=False)

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty
date,,,,,,,,,
2022-01-02 22:00:00,115.084,115.089,115.117,115.054,115.100,115.132,115.198,115.115,377
2022-01-02 23:00:00,115.089,115.137,115.151,115.077,115.132,115.151,115.165,115.104,3637
2022-01-03 00:00:00,115.137,115.274,115.287,115.116,115.151,115.286,115.298,115.130,4307
2022-01-03 01:00:00,115.274,115.221,115.274,115.176,115.286,115.233,115.286,115.189,3429
2022-01-03 02:00:00,115.221,115.270,115.272,115.201,115.233,115.284,115.285,115.212,2138

In [39]:
# ma =[3]
# for x in ma:
#     df_ma[f'MA_{x}'] =df_ma.mid_c.rolling(window=x).mean()


fast = 8
slow = 32

df[f'MA_fast'] =df.askclose.rolling(window=fast).mean()
df[f'MA_slow'] =df.askclose.rolling(window=slow).mean()

df.tail()

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,MA_5,MA_96,MA_fast,MA_slow,signal,position
date,,,,,,,,,,,,,,,
2022-03-31 20:00:00,121.717,121.647,121.770,121.605,121.732,121.777,121.786,121.686,4443,121.6510,122.648281,121.566250,121.848781,0,0.0
2022-03-31 21:00:00,121.618,121.661,121.708,121.618,121.746,121.704,121.760,121.697,299,121.6786,122.644562,121.590375,121.842219,0,0.0
2022-03-31 22:00:00,121.660,121.747,121.811,121.654,121.704,121.766,121.832,121.699,5664,121.7182,122.639146,121.644625,121.834281,0,0.0
2022-03-31 23:00:00,121.748,121.739,121.905,121.734,121.767,121.753,121.918,121.749,5619,121.7462,122.633677,121.684750,121.827750,0,0.0
2022-04-01 00:00:00,121.740,122.111,122.190,121.738,121.753,122.128,122.205,121.752,22332,121.8256,122.632521,121.755000,121.834750,0,0.0

In [40]:
df['signal'] = np.where(df.MA_fast>df.MA_slow, 1, 0)
df["position"] = df.signal.diff()

In [42]:
df.reset_index
df.tail(55)

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,MA_5,MA_96,MA_fast,MA_slow,signal,position
date,,,,,,,,,,,,,,,
2022-03-29 18:00:00,122.820,122.924,122.934,122.773,122.834,122.939,122.949,122.788,7699,122.7536,122.564583,122.813250,123.447812,0,0.0
2022-03-29 19:00:00,122.925,122.870,122.945,122.856,122.939,122.886,122.961,122.871,6381,122.7858,122.583052,122.725750,123.411031,0,0.0
2022-03-29 20:00:00,122.870,122.888,122.901,122.846,122.884,122.903,122.917,122.859,1807,122.8460,122.601500,122.730375,123.387312,0,0.0
2022-03-29 21:00:00,122.842,122.861,122.875,122.835,122.906,122.898,122.906,122.888,266,122.8922,122.621396,122.806875,123.358344,0,0.0
2022-03-29 22:00:00,122.863,122.976,122.988,122.839,122.899,122.993,123.003,122.858,5188,122.9238,122.639760,122.840375,123.340750,0,0.0
2022-03-29 23:00:00,122.974,123.119,123.199,122.831,122.991,123.133,123.215,122.847,11227,122.9626,122.659677,122.906750,123.336000,0,0.0
2022-03-30 00:00:00,123.119,122.481,123.119,122.408,123.132,122.498,123.135,122.423,39994,122.8850,122.672896,122.885625,123.307469,0,0.0
2022-03-30 01:00:00,122.481,122.334,122.529,121.964,122.499,122.352,122.544,121.980,42731,122.7748,122.684583,122.825250,123.271781,0,0.0
2022-03-30 02:00:00,122.334,121.901,122.344,121.774,122.351,121.918,122.362,121.796,35074,122.5788,122.689479,122.697625,123.220156,0,0.0
2022-03-30 03:00:00,121.901,121.654,121.955,121.303,121.919,121.673,121.974,121.322,35311,122.3148,122.690323,122.546000,123.152375,0,0.0
2022-03-30 04:00:00,121.654,121.891,121.904,121.524,121.675,121.909,121.921,121.545,18786,122.0700,122.693125,122.421750,123.089125,0,0.0
2022-03-30 05:00:00,121.890,121.994,122.010,121.773,121.909,122.013,122.027,121.789,13310,121.9730,122.697083,122.311125,123.029625,0,0.0
2022-03-30 06:00:00,121.992,121.931,122.073,121.608,122.012,121.947,122.091,121.628,22631,121.8920,122.699885,122.180375,122.960500,0,0.0
2022-03-30 07:00:00,121.931,121.874,122.000,121.601,121.946,121.890,122.016,121.619,24863,121.8864,122.702292,122.025000,122.906625,0,0.0
2022-03-30 08:00:00,121.874,121.605,121.881,121.515,121.891,121.621,121.898,121.531,16062,121.8760,122.702656,121.915375,122.827531,0,0.0
2022-03-30 09:00:00,121.605,121.875,121.962,121.563,121.620,121.890,121.976,121.580,14013,121.8722,122.705010,121.857625,122.770969,0,0.0
2022-03-30 10:00:00,121.875,121.921,122.036,121.737,121.889,121.936,122.056,121.752,16644,121.8568,122.704542,121.859875,122.726219,0,0.0
2022-03-30 11:00:00,121.920,121.723,121.945,121.622,121.936,121.738,121.959,121.636,12980,121.8150,122.702500,121.868000,122.680969,0,0.0
2022-03-30 12:00:00,121.722,121.842,121.891,121.653,121.738,121.856,121.905,121.671,18961,121.8082,122.700396,121.861375,122.633500,0,0.0
2022-03-30 13:00:00,121.843,121.899,122.236,121.635,121.856,121.914,122.255,121.654,32086,121.8668,122.695479,121.849000,122.580562,0,0.0
2022-03-30 14:00:00,121.898,122.006,122.022,121.719,121.914,122.020,122.037,121.737,27609,121.8928,122.692500,121.858125,122.533875,0,0.0
2022-03-30 15:00:00,122.005,121.947,122.046,121.830,122.020,121.962,122.058,121.842,17493,121.8980,122.689531,121.867125,122.483250,0,0.0
2022-03-30 16:00:00,121.947,121.890,121.974,121.867,121.960,121.904,121.989,121.881,11264,121.9312,122.685156,121.902500,122.426125,0,0.0
2022-03-30 17:00:00,121.890,121.915,121.919,121.861,121.905,121.929,121.932,121.874,8216,121.9458,122.680229,121.907375,122.368969,0,0.0
2022-03-30 18:00:00,121.916,121.736,121.920,121.731,121.930,121.751,121.933,121.746,10151,121.9132,122.673458,121.884250,122.313750,0,0.0
2022-03-30 19:00:00,121.736,121.817,121.857,121.735,121.749,121.829,121.872,121.748,13090,121.8750,122.667594,121.895625,122.258844,0,0.0
2022-03-30 20:00:00,121.816,121.765,121.841,121.765,121.829,121.896,121.896,121.795,3987,121.8618,122.662781,121.900625,122.228531,0,0.0
2022-03-30 21:00:00,121.811,121.852,121.867,121.810,121.932,121.901,121.932,121.846,539,121.8612,122.661083,121.899000,122.216500,0,0.0
2022-03-30 22:00:00,121.854,121.904,121.983,121.830,121.905,121.918,122.001,121.852,4630,121.8590,122.660844,121.886250,122.191281,0,0.0
2022-03-30 23:00:00,121.904,122.018,122.157,121.896,121.919,122.031,122.175,121.913,8769,121.9150,122.663125,121.894875,122.173438,0,0.0
2022-03-31 00:00:00,122.020,122.279,122.447,121.896,122.031,122.295,122.464,121.912,48468,122.0082,122.670240,121.943750,122.161813,0,0.0
2022-03-31 01:00:00,122.278,122.133,122.448,122.085,122.295,122.146,122.465,122.102,28319,122.0582,122.677208,121.970875,122.140281,0,0.0
2022-03-31 02:00:00,122.133,122.169,122.183,121.958,122.145,122.185,122.199,121.974,17250,122.1150,122.682125,122.025125,122.116719,0,0.0
2022-03-31 03:00:00,122.174,122.326,122.382,122.143,122.189,122.341,122.398,122.159,12249,122.1996,122.687792,122.089125,122.099687,0,0.0
2022-03-31 04:00:00,122.326,122.219,122.349,122.182,122.342,122.233,122.364,122.196,13772,122.2400,122.692854,122.131250,122.078750,1,1.0
2022-03-31 05:00:00,122.219,122.049,122.272,122.049,122.234,122.065,122.288,122.065,13677,122.1940,122.698552,122.151750,122.052719,1,0.0
2022-03-31 06:00:00,122.049,121.562,122.049,121.528,122.064,121.580,122.065,121.546,30186,122.0808,122.697948,122.109500,122.008562,1,0.0
2022-03-31 07:00:00,121.561,121.632,121.685,121.332,121.576,121.647,121.702,121.349,25197,121.9732,122.697042,122.061500,121.962125,1,0.0
2022-03-31 08:00:00,121.632,122.172,122.221,121.632,121.646,122.186,122.234,121.646,29660,121.9422,122.702385,122.047875,121.952375,1,0.0
2022-03-31 09:00:00,122.171,121.937,122.172,121.911,122.186,121.954,122.187,121.927,15566,121.8864,122.704427,122.023875,121.939938,1,0.0
2022-03-31 10:00:00,121.938,121.667,121.969,121.660,121.954,121.681,121.982,121.676,11192,121.8096,122.699500,121.960875,121.932531,1,0.0
2022-03-31 11:00:00,121.667,121.621,121.798,121.586,121.682,121.637,121.814,121.599,13671,121.8210,122.695438,121.872875,121.931406,0,-1.0
2022-03-31 12:00:00,121.622,121.612,121.847,121.536,121.636,121.626,121.861,121.553,20514,121.8168,122.691521,121.797000,121.922562,0,0.0
2022-03-31 13:00:00,121.611,121.498,121.754,121.498,121.626,121.511,121.769,121.511,27402,121.6818,122.686062,121.727750,121.906875,0,0.0
2022-03-31 14:00:00,121.498,121.317,121.817,121.291,121.512,121.332,121.831,121.307,33781,121.5574,122.677979,121.696750,121.887656,0,0.0
2022-03-31 15:00:00,121.317,121.418,121.508,121.272,121.331,121.432,121.523,121.289,21196,121.5076,122.670615,121.669875,121.873344,0,0.0
2022-03-31 16:00:00,121.418,121.552,121.668,121.415,121.431,121.566,121.683,121.428,10487,121.4934,122.664448,121.592375,121.871625,0,0.0
2022-03-31 17:00:00,121.553,121.555,121.626,121.522,121.567,121.568,121.641,121.536,7434,121.4818,122.658781,121.544125,121.861562,0,0.0
2022-03-31 18:00:00,121.554,121.600,121.606,121.519,121.568,121.613,121.620,121.532,7235,121.5022,122.654823,121.535625,121.851469,0,0.0
2022-03-31 19:00:00,121.599,121.717,121.762,121.560,121.613,121.731,121.779,121.573,8637,121.5820,122.652094,121.547375,121.851250,0,0.0
2022-03-31 20:00:00,121.717,121.647,121.770,121.605,121.732,121.777,121.786,121.686,4443,121.6510,122.648281,121.566250,121.848781,0,0.0
2022-03-31 21:00:00,121.618,121.661,121.708,121.618,121.746,121.704,121.760,121.697,299,121.6786,122.644562,121.590375,121.842219,0,0.0
2022-03-31 22:00:00,121.660,121.747,121.811,121.654,121.704,121.766,121.832,121.699,5664,121.7182,122.639146,121.644625,121.834281,0,0.0
2022-03-31 23:00:00,121.748,121.739,121.905,121.734,121.767,121.753,121.918,121.749,5619,121.7462,122.633677,121.684750,121.827750,0,0.0
2022-04-01 00:00:00,121.740,122.111,122.190,121.738,121.753,122.128,122.205,121.752,22332,121.8256,122.632521,121.755000,121.834750,0,0.0

Exception in thread Thread-409311 (_handle_reconnect):
Traceback (most recent call last):
  File "C:\Users\HPENVY\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\HPENVY\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\socketio\client.py", line 552, in _handle_reconnect
    self.connect(self.connection_url,
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\socketio\client.py", line 267, in connect
    self.eio.connect(url, headers=headers, transports=transports,
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\engineio\client.py", line 165, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\engineio\client.py", line 303, in _connect_polling
    if self._connect_websocket(url, headers, engineio_path):
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\engineio\client.py", line 339, in _connect_websocket
    ws = websocket.create_connection(
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\websocket\_core.py", line 601, in create_connection
    websock.connect(url, **options)
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\websocket\_http.py", line 198, in _open_socket
    raise error
  File "c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

In [41]:
pipcost = .91
lot_size = 10

begin_prices = []
end_prices = []

profits = 0
profit_collect =  [0]

#getting open and close price of each position
for i, row in df.iterrows():
    if row['position']==1:
        begin_prices.append(float(row['askopen']))
    if row['position']==-1:
        end_prices.append(float(row['bidopen']))



#calculate the profit or loss
for i in range(len(begin_prices)-1):
    profit = (end_prices[i]-begin_prices[i])
    profits += profit
    profit_collect.append(profits)


print(str(int(profits)))

7

In [5]:
import requests
import defs
import pandas as pd


session = requests.Session()

ins_df = pd.read_pickle("instruments.pkl")

our_curr = ['EUR', 'USD', 'GBP', 'JPY', 'CHF', 'NZD', 'CAD']




def fetch_candles(pair_name, count, granularity):
    url = f"{defs.OANDA_URL}/instruments/{pair_name}/candles"
    params = dict(
        count = count,
        granularity = granularity,
        price = "MBA"
    )
    response = session.get(url, params=params, headers=defs.SECURE_HEADER)
    return response.status_code, response.json()

In [2]:
import datetime as dt
from dateutil.parser import *
from oanda_api import OandaAPI
from instrument import Instrument
import pandas as pd
import utils





INCREMENTS = {
    'M1' : 1,
    #'H1' : 60,
    #'H4' : 240
}


def get_his_data_filename(pair, granularity):
    return f"his_data/{pair}_{granularity}.pkl"




def get_utc_dt_from_string(date_str):
    d = parse(date_str)
    return d.replace(tzinfo=dt.timezone.utc)
###################################################################
#get candles df; gets candles from the json response 
# sves it in a dictionanary 
#then turns it to a dataframe
###########################################################
def get_candles_df(json_response):

    prices = ['mid', 'bid', 'ask']
    ohlc = ['o', 'h', 'l', 'c']

    our_data = []
    for candle in json_response['candles']:
        if candle['complete'] == False:
            continue
        new_dict = {}
        new_dict['time'] = candle['time']
        new_dict['volume'] = candle['volume']
        for price in prices:
            for oh in ohlc:
                new_dict[f"{price}_{oh}"] = candle[price][oh]
        our_data.append(new_dict)
    return pd.DataFrame.from_dict(our_data)


###################################################################
#creating the file; set the candle count to 2000,
# set the start and end dates of the data you want to collect
# loop through the set dates collecting the data and appending it to the candles df
#  finaly drop duplicatevalues, sort the result and save it as a pickle file
###########################################################

def create_file(pair, granularity, api):
    candle_count = 2000
    time_step = INCREMENTS[granularity] * candle_count

    end_date = get_utc_dt_from_string("2022-03-16 23:59:59")
    date_from = get_utc_dt_from_string("2022-02-21 00:00:00")

    candle_dfs = []

    date_to = date_from
    while date_to < end_date:
        date_to = date_from + dt.timedelta(minutes=time_step)
        if date_to > end_date:
            date_to = end_date
                
        code, json_data = api.fetch_candles(pair,
                granularity=granularity,
                date_from=date_from,
                date_to=date_to)
        if code == 200 and len(json_data['candles']) > 0:
            candle_dfs.append(get_candles_df(json_data))
        elif code != 200:
            print("ERROR", pair, granularity, date_from, date_to)
            break
        date_from = date_to

    final_df = pd.concat(candle_dfs)
    final_df.drop_duplicates(subset='time', inplace=True)
    final_df.sort_values(by='time', inplace=True)
    final_df.to_pickle(utils.get_his_data_filename(pair, granularity))
    print(f"{pair} {granularity} {final_df.iloc[0].time}  {final_df.iloc[-1].time}")


###################################################################
# run collection; set the currecies you want to trade in the pair list
# create an object from the oanda api class
# loop through the granulity list,
# create tradable currecy pairs from the currecy list using the instruments module(file)
# call the create file function and pass in the values
###########################################################


def run_collection():
    pair_list = "EUR,USD,JPY,CHF,SGD,GBP"
    api = OandaAPI()
    for g in INCREMENTS.keys():
        for i in Instrument.get_pairs_from_string(pair_list):
            create_file(i, g, api)

run_collection()

NameError: name 'get_his_data_filename' is not defined

In [14]:
run_collection()

TypeError: OandaAPI.fetch_candles() got an unexpected keyword argument 'date_from'

In [12]:
pip install fxcmpy

Collecting fxcmpy
  Downloading fxcmpy-1.2.10-py3-none-any.whl (28 kB)
Collecting websocket-client
  Downloading websocket_client-1.3.2-py3-none-any.whl (54 kB)
Requirement already satisfied: pandas in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from fxcmpy) (1.4.0)
Requirement already satisfied: requests[socks] in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from fxcmpy) (2.27.1)
Collecting python-engineio==3.9
  Downloading python_engineio-3.9.0-py2.py3-none-any.whl (119 kB)
Collecting configparser
  Downloading configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting python-socketio==4.4
  Downloading python_socketio-4.4.0-py2.py3-none-any.whl (50 kB)
Requirement already satisfied: six>=1.9.0 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from python-engineio==3.9->fxcmpy) (1.16.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from pandas->fxcmpy) (2021.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from pandas->fxcmpy) (1.22.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from pandas->fxcmpy) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from requests[socks]->fxcmpy) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from requests[socks]->fxcmpy) (2.0.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from requests[socks]->fxcmpy) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hpenvy\desktop\workspace\python real\venv\venv\lib\site-packages (from requests[socks]->fxcmpy) (1.26.8)
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: python-engineio, PySocks, websocket-client, python-socketio, configparser, fxcmpy
Successfully installed PySocks-1.7.1 configparser-5.2.0 fxcmpy-1.2.10 python-engineio-3.9.0 python-socketio-4.4.0 websocket-client-1.3.2
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\Users\HPENVY\Desktop\workspace\python real\venv\venv\Scripts\python.exe -m pip install --upgrade pip' command.